---
- hosts: all
  tasks:

  - community.general.homebrew:
      name:
        - terminal-notifier

  - community.general.homebrew_cask:
      name:
        - 1password
        # - authy
        - bettertouchtool
        - dash
        - firefox
        - google-chrome
#        - irccloud
        - iterm2
        - keepingyouawake
        - meetingbar
        - moom
        - slack
        - visual-studio-code
        - zoom
