---
- hosts: all
  tasks:

  # Required to make TouchID sudo work in iTerm
  # https://github.com/fabianishere/pam_reattach
  # - homebrew:
  #    pkg: fabianishere/personal/pam_reattach

  - name: enable touchid pam
    become: yes
    copy:
      dest: /etc/pam.d/sudo_local
      content: |
        auth  sufficient  pam_tid.so

  - name: symlink homebrew bash completion into etc
    become: yes
    file:
      src: /opt/homebrew/etc/bash_completion
      path: /etc/bash_completion
      force: yes
      state: link

  - name: enable locate searching
    become: yes
    command: launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist
    args:
      creates: /var/db/locate.database
    register: enable_locate_result
    changed_when: "'stderr' in enable_locate_result and 'service already loaded' not in enable_locate_result.stderr"

  - name: symlink gitconfig
    file:
      src: "{{playbook_dir}}/files/gitconfig"
      path: "{{ ansible_user_dir }}/.gitconfig"
      state: link
  - name: create global gitignore
    file:
      src: "{{playbook_dir}}/files/gitignore"
      path: "{{ ansible_user_dir }}/.gitignore_global"
      state: link

  - name: make ssh dir
    file:
      path: "{{ ansible_user_dir }}/.ssh"
      state: directory
  - name: make ssh config.d dir
    file:
      path: "{{ ansible_user_dir }}/.ssh/config.d"
      state: directory
  - name: symlink ssh config
    file:
      src: "{{playbook_dir}}/files/sshconfig"
      path: "{{ ansible_user_dir }}/.ssh/config"
      state: link

  - name: install updated bash
    homebrew:
       pkg: bash
  - name: allow Homebrew bash as shell
    become: yes
    lineinfile:
      path: /etc/shells
      line: /opt/homebrew/bin/bash
  - name: switch shell to bash
    become: yes
    user:
      name: glen
      shell: /opt/homebrew/bin/bash

  - name: prep for multiple bash profile overrides
    file:
      path: "{{ ansible_user_dir }}/.profile.d"
      state: directory
  - name: setup bash profile
    copy:
      content: |
        for file in {{ ansible_user_dir }}/.profile.d/*.sh; do
          source $file
        done
        source {{ playbook_dir }}/files/bash-setup.sh
      dest: "{{ ansible_user_dir }}/.profile"
  - name: setup bashrc to ensure __git_ps1 works in subshells
    copy:
      content: |
        source /opt/homebrew/etc/bash_completion.d/git-prompt.sh
      dest: "{{ ansible_user_dir }}/.bashrc"
