---
- hosts: all
  tasks:
  - name: NSGlobalDomain defaults
    osx_defaults:
      domain: NSGlobalDomain
      key: "{{ item.key }}"
      type: "{{ item.type }}"
      value: "{{ item.value }}"
      state: present
    with_items:
      - key: AppleLocale
        type: string
        value: en_GB
      - key: AppleLanguages
        type: array
        value: ["en-GB"]
      - key: AppleKeyboardUIMode # Focus on all controls
        type: int
        value: 3
      - key: com.apple.swipescrolldirection # The old way
        type: bool
        value: false

  - name: com.apple.driver.AppleBluetoothMultitouch.trackpad defaults
    osx_defaults:
      domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
      key: "{{ item.key }}"
      type: "{{ item.type }}"
      value: "{{ item.value }}"
      state: present
    with_items:
      - key: Clicking # Tap to click
        type: int
        value: true