---
- hosts: all
  tasks:

  - name: create dev dirs
    file:
      state: directory
      path: "{{ item }}"
    with_items:
      - "{{ ansible_user_dir}}/Development"
      - "{{ ansible_user_dir }}/Development/GitHub"

  - community.general.homebrew:
      name:
        - ag
        - asdf
        - awscli
        - bash-completion
        - circleci
        - cloc
        - coreutils
        - docker-completion
        - docker-compose-completion
        - git
        - git-cola
        - gpg2
        - jq
        - shellcheck
        - watch
        - wget

  - community.general.homebrew_cask:
      name:
        - aws-vault
        - docker
        - tuple
        - sqlpro-studio

  - include_role:
      name: markosamuli.asdf
    vars:
      asdf_version: v0.8.1
      asdf_init_shell: false
      asdf_plugins:
        - name: golang
          global: 1.16.4
          versions:
            - 1.16.4

  - copy:
      dest: "{{ ansible_user_dir }}/.profile.d/asdf.sh"
      content: |
        source $HOME/.asdf/asdf.sh
        source $HOME/.asdf/completions/asdf.bash
