---
- hosts: all
  tasks:
  - osx_defaults:
      domain: com.apple.dock
      key: "{{ item.key }}"
      type: "{{ item.type }}"
      value: "{{ item.value }}"
      state: present
    with_items:
      - key: autohide
        type: bool
        value: true
      - key: show-recents
        type: bool
        value: false
      - key: magnification
        type: bool
        value: false
      - key: autohide-delay
        type: float
        value: 0
      - key: orientation
        type: string
        value: left
      - key: tilesize
        type: int
        value: 40
      - key: showAppExposeGestureEnabled
        type: bool
        value: true
    notify:
      - killall dock

  - homebrew:
      pkg:
        - dockutil

  - include_role:
      name: fubarhouse.macdock
    vars:
      dockitems_remove_all: true
      dockitems_enabled:
        - name: Firefox
          path: /Applications/Firefox.app
          pos: 1
        - name: iTerm
          path: /Applications/iTerm.app
          pos: 2
        - name: Vistual Studio Code
          path: /Applications/Visual Studio Code.app
          pos: 3
        - name: Calendar
          path: /Applications/Calendar.app
          pos: 4
        - name: Slack
          path: /Applications/Slack.app
          pos: 5
        - name: Google Chrome
          path: /Applications/Google Chrome.app
          pos: 6
        - name: Authy Desktop
          path: /Applications/Authy Desktop.app
          pos: 7
        - name: zoom.us
          path: /Applications/zoom.us.app
          pos: 8
        - name: Notes
          path: /Applications/Notes.app
          pos: 9

  handlers:
    - name: killall dock
      command: killall Dock