brew 'aws-elasticbeanstalk'
brew 'awscli'
brew 'azure-cli'
brew 'bash-completion'
brew 'certbot'
brew 'colordiff'
brew 'ffmpeg'
brew 'git-cola'
brew 'git'
brew 'go'
brew 'gpg'
brew 'heroku'
brew 'hub'
brew 'ike-scan'
brew 'jq'
brew 'mas'
brew 'n'
brew 'oath-toolkit'
brew 'pandoc'
brew 'pipenv'
brew 'p7zip'
brew 'postgresql'
brew 'pwgen'
brew 'redis'
brew 'https://gist.githubusercontent.com/lalyos/28b35c29d4f8d2c1f293/raw/sshpass.rb'
brew 'telnet'
brew 'terminal-notifier'
brew 'terraform'
brew 'terraform_landscape'
brew 'wget'
brew 'yarn', ignore_dependencies: true
brew 'youtube-dl'

cask 'atom'
cask 'avast-security'
cask 'bettertouchtool'
cask 'coconutbattery'
cask 'cyberduck'
cask 'dash'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'google-backup-and-sync'
cask 'google-chrome'
cask 'growlnotify'
cask 'iterm2'
cask 'keepingyouawake'
cask 'keybase'
cask 'kitematic'
cask 'lastpass'
cask 'microsoft-azure-storage-explorer'
cask 'moom'
cask 'multifirefox'
cask 'powershell'
cask 'psequel'
cask 'sketch'
cask 'sqlpro-for-mssql'
cask 'steam'
cask 'vagrant'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'vlc'

mas 'LastPass Password Manager', id: 926036361
mas 'Microsoft Remote Desktop 8.0', id: 715768417
mas 'Slack', id: 803453959
mas 'Growl', id: 467939042
