---
- hosts: all
  become: true
  tasks:
  - name: enable touchid pam
    lineinfile:
      path: /etc/pam.d/sudo
      line: auth  sufficient  pam_tid.so
      insertbefore: smartcard

  - name: symlink homebrew bash completion into etc
    file:
      src: /usr/local/etc/bash_completion
      path: /etc/bash_completion
      state: link
      owner: "{{user}}"

  - name: symlink gitconfig
    file:
      src: "{{playbook_dir}}/files/gitconfig"
      path: "~{{user}}/.gitconfig"
      state: link
      owner: "{{user}}"

  - name: make ssh dir
    file:
      path: "~{{user}}/.ssh"
      state: directory
      owner: "{{user}}"
  - name: make ssh config.d dir
    file:
      path: "~{{user}}/.ssh/config.d"
      state: directory
      owner: "{{user}}"
  - name: symlink ssh config
    file:
      src: "{{playbook_dir}}/files/sshconfig"
      path: "~{{user}}/.ssh/config"
      state: link
      owner: "{{user}}"

  - name: symlink bash setup
    file:
      src: "{{playbook_dir}}/files/bash-setup.sh"
      path: "~{{user}}/.bash-setup"
      state: link
      owner: "{{user}}"
  - name: setup bash profile
    template:
      src: files/profile.j2
      dest: "~{{user}}/.profile"
      owner: "{{user}}"

  - name: create yarn global directory
    file:
      path: "~{{user}}/.config/yarn/global"
      state: directory
      owner: "{{user}}"
  - name: symlink yarn global package.json
    file:
      src: "{{playbook_dir}}/files/yarn-global.package.json"
      dest: "~{{user}}/.config/yarn/global/package.json"
      state: link
      owner: "{{user}}"

  - include_tasks: dns.yml

  - name: install pip stuff
    become_user: "{{user}}"
    pip:
      executable: pip3
      name: "{{item}}"
    with_items:
      - jmespath-terminal
      - autopep8
      - twine
      - pypandoc

  - name: install circleci CLI
    shell: |
      curl -o /usr/local/bin/circleci \
        https://circle-downloads.s3.amazonaws.com/releases/build_agent_wrapper/circleci
    args:
      creates: /usr/local/bin/circleci
  - name: set circleci bin mode
    file:
      path: /usr/local/bin/circleci
      mode: 0755
