---
- hosts: all
  become: true
  tasks:
  - name: enable touchid pam
    lineinfile:
      path: /etc/pam.d/sudo
      line: auth  sufficient  pam_tid.so
      insertbefore: smartcard

  - name: symlink homebrew bash completion into etc
    file:
      src: /usr/local/etc/bash_completion
      path: /etc/bash_completion
      state: link
      owner: "{{user}}"

  - name: symlink gitconfig
    file:
      src: "{{playbook_dir}}/files/gitconfig"
      path: "~{{user}}/.gitconfig"
      state: link
      owner: "{{user}}"

  - name: make ssh dir
    file:
      path: "~{{user}}/.ssh"
      state: directory
      owner: "{{user}}"
  - name: make ssh config.d dir
    file:
      path: "~{{user}}/.ssh/config.d"
      state: directory
      owner: "{{user}}"
  - name: symlink ssh config
    file:
      src: "{{playbook_dir}}/files/sshconfig"
      path: "~{{user}}/.ssh/config"
      state: link
      owner: "{{user}}"

  - name: setup bash profile
    copy:
      content: |
        source {{playbook_dir}}/files/bash-setup.sh
      dest: "~{{user}}/.profile"
      owner: "{{user}}"
  - name: setup bashrc to ensure __git_ps1 works in subshells
    copy:
      content: |
        source /usr/local/etc/bash_completion.d/git-prompt.sh
      dest: "~{{user}}/.bashrc"
      owner: "{{user}}"

  - name: create yarn global directory
    file:
      path: "~{{user}}/.config/yarn/global"
      state: directory
      owner: "{{user}}"
  - name: symlink yarn global package.json
    file:
      src: "{{playbook_dir}}/files/yarn-global.package.json"
      dest: "~{{user}}/.config/yarn/global/package.json"
      state: link
      owner: "{{user}}"

  - include_tasks: dns.yml

  - name: install ruby stuff
    gem:
      user_install: no
      name: "{{item}}"
      state: latest
    with_items:
      - bundler

  - name: install pip stuff
    become_user: "{{user}}"
    pip:
      executable: pip3
      name: "{{item}}"
    with_items:
      - jmespath-terminal
      - autopep8
      - twine
      - pypandoc
      - awslogs

  - name: install circleci CLI
    get_url:
      url: https://circle-downloads.s3.amazonaws.com/releases/build_agent_wrapper/circleci
      url_username: anon
      dest: /usr/local/bin/circleci
      mode: 0755

  - name: install lectl
    get_url:
      url: https://raw.githubusercontent.com/sahsanu/lectl/36bbc26a605f80737048c92a5e6479a29e6f50d1/lectl
      url_username: anon
      dest: /usr/local/bin/lectl
      mode: 0755
